web:
  svc:
    pkg: httpd #Web Package
    name: httpd #Systemd Service Name
    port: 80 #Web Service Port
  admin:
    email: admin@example.com
  file:
    config: 
      src: httpd.conf.j2
      dst: /etc/httpd/conf/httpd.conf
    content: 
      src: index.html.j2
      dst: /var/www/html/index.html

